### PR TITLE
Add teardown option

### LINKED ISSUE #34: Add a new clearup stage for timeit
I propose to add a clearup stage for timeit. The reason is today when I run perf to benchmark a program, the program will generate a cache file first time and then always use it. I wish to have a separate clear stage, just like the setup stage, to clean it.

### PR DESCRIPTION
**Pull request by gagoman**
Closes #34 

---

I want to add some extra tests and update the doc. Right now PR is to get the feedback if there are something to fix/improve. I have checked if I had made breaking changes. Seems like no.

### CODE REVIEW

**Comment by vstinner** [comment]
> I have checked if I had made breaking changes.

The tests pass on this PR, so it's fine :-) If you would break something, the problem would be that perf lacks a new test in that case! Don't worry.

**Comment by gagoman** [comment]
I've added docs. Working on `Timer` tests now.

**Comment by gagoman** [comment]
@vstinner which docs are missing?

I've added some tests for the `Timer`. They duplicate code so I'm not sure that they are good.

**Comment by vstinner** [comment]
Oh, I see the documentation. Maybe I missed it at the first read, sorry. I now merged your new parameter, thanks.

**Pull request merged**
